[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"


[project]
name = "cte2"
version = "1.0.0"
authors = [
  { name = "Yujin(Will) Kang", email = "yjkang@snu.ac.kr" },
  ]
description = "python package for calculating  the coefficient of thermal expansion with universal machine learning interatomic potentials"
readme = "README.md"
requires-python = ">=2.7"

dependencies = [
    "sevenn",
    "numpy",
    "pymatgen",
    "ase",
    "spglib"
    ]

[project.scripts]
cte2 = "cte2.main:main"
cte2-run = "cte2.main:main"

[tool.setuptools]
packages = [
    "cte2",
    "cte2.structure",
    "cte2.phonon",
    "cte2.util",
]

[project.urls]
Homepage = "https://github.com/dnlf1ff/cte2"
Issues = "https://github.com/dnlf1ff/cte2/issues"
